<div class="row">

	<div class="col-md-12">
		<div class="col-md-1 center-text">
			<span class="glyphicon glyphicon-user forum-avatar"></span>	
		</div>
		<div class="col-md-9">
			<div class="forum-title-text">
				<a href="#">{{title}}</a>
			</div>
		</div>
		<div class="col-md-2">
			<div class="forum-count-text">
				<b class="glyphicon glyphicon-stats"></b>
				<strong>
					{{#views}}
					{{/views}}
				</strong>
			</div>
		</div>

	</div>

</div>